### ISSUE TITLE
View is flattened when converted to a Button

### ISSUE THREAD

**Issue by wasa4587** [Supernova-Studio/public-issue-tracker#93]
### Issue
Basically, It's converting
```
          <View
            style={styles.nextButtonRectangularView}>
            <View
              style={styles.nextButtonView}>
              <Text
                style={styles.labelText}>NEXT</Text>
              <Text
                style={styles.iconText}></Text>
            </View>
          </View>
```

into 

```
          <TouchableOpacity
            onPress={this.onNextButtonRectangularPressed}
            style={styles.nextButtonRectangularButton}>
            <Text
              style={styles.nextButtonRectangularButtonText}>NEXT</Text>
          </TouchableOpacity>
```

This makes me choose between losing icons or use transitions

### Context
Supernova V6.0
Mac Mojave 10.14.3

When I convert a View with nested components into a button, almost all child components disappear

### Expected result
I would expect something like this
```
          <TouchableOpacity
            style={styles.nextButtonRectangularView}>
            <View
              style={styles.nextButtonView}>
              <Text
                style={styles.labelText}>NEXT</Text>
              <Text
                style={styles.iconText}></Text>
            </View>
          </TouchableOpacity>
```

### Current result
```
          <TouchableOpacity
            onPress={this.onNextButtonRectangularPressed}
            style={styles.nextButtonRectangularButton}>
            <Text
              style={styles.nextButtonRectangularButtonText}>NEXT</Text>
          </TouchableOpacity>
```

### Screenshots
before
<img width="146" alt="Screen Shot 2019-03-10 at 3 57 39 PM" src="https://user-images.githubusercontent.com/2035706/54138149-8d13cb80-43e4-11e9-9259-f3d457f786de.png">
after
<img width="128" alt="Screen Shot 2019-03-10 at 3 57 44 PM" src="https://user-images.githubusercontent.com/2035706/54138172-94d37000-43e4-11e9-9982-0024c086cf69.png">

before
<img width="149" alt="Screen Shot 2019-03-10 at 4 00 36 PM" src="https://user-images.githubusercontent.com/2035706/54138181-9866f700-43e4-11e9-9e37-70247d30ee4f.png">
after
<img width="130" alt="Screen Shot 2019-03-10 at 4 00 44 PM" src="https://user-images.githubusercontent.com/2035706/54138189-9b61e780-43e4-11e9-88f3-09720d54649f.png">

**Comment by artufimtcev** [comment]
We have improved button conversion and analysis in 6.1, so this should be fixed

**Comment by wasa4587** [comment]
<img width="315" alt="Screen Shot 2019-03-18 at 2 57 19 PM" src="https://user-images.githubusercontent.com/2035706/54563175-29fad980-498e-11e9-8483-5419e0d06fef.png">
The issue remains in version 6.2
